# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(762, 582)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.max_fig3 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.max_fig3.setGeometry(QtCore.QRect(600, 420, 91, 30))
        self.max_fig3.setDecimals(5)
        self.max_fig3.setMinimum(-10000099.0)
        self.max_fig3.setMaximum(10000099.0)
        self.max_fig3.setObjectName("max_fig3")
        self.line_4 = QtWidgets.QFrame(self.centralWidget)
        self.line_4.setGeometry(QtCore.QRect(490, 140, 20, 121))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.zoom_ext = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.zoom_ext.setGeometry(QtCore.QRect(490, 280, 91, 30))
        self.zoom_ext.setDecimals(2)
        self.zoom_ext.setMinimum(-10000099.0)
        self.zoom_ext.setMaximum(10000099.0)
        self.zoom_ext.setObjectName("zoom_ext")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(540, 90, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.zoom_y = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.zoom_y.setGeometry(QtCore.QRect(310, 280, 91, 30))
        self.zoom_y.setDecimals(2)
        self.zoom_y.setMinimum(-10000099.0)
        self.zoom_y.setMaximum(10000099.0)
        self.zoom_y.setObjectName("zoom_y")
        self.cbx_legend = QtWidgets.QComboBox(self.centralWidget)
        self.cbx_legend.setGeometry(QtCore.QRect(380, 90, 101, 30))
        self.cbx_legend.setObjectName("cbx_legend")
        self.cbx_legend.addItem("")
        self.cbx_legend.addItem("")
        self.cbx_legend.addItem("")
        self.cbx_legend.addItem("")
        self.cbx_legend.addItem("")
        self.cbx_legend.addItem("")
        self.cbx_legend.addItem("")
        self.cbx_legend.addItem("")
        self.cbx_legend.addItem("")
        self.cbx_legend.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pb_comp = QtWidgets.QPushButton(self.centralWidget)
        self.pb_comp.setGeometry(QtCore.QRect(620, 490, 121, 30))
        self.pb_comp.setObjectName("pb_comp")
        self.label_14 = QtWidgets.QLabel(self.centralWidget)
        self.label_14.setGeometry(QtCore.QRect(290, 380, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.cbx_cat_c3 = QtWidgets.QComboBox(self.centralWidget)
        self.cbx_cat_c3.setGeometry(QtCore.QRect(520, 160, 200, 30))
        self.cbx_cat_c3.setObjectName("cbx_cat_c3")
        self.cbx_cat_c3.addItem("")
        self.cbx_cat_c3.addItem("")
        self.cbx_cat_c3.addItem("")
        self.cbx_cat_c3.addItem("")
        self.cbx_cat_c3.addItem("")
        self.cbx_cat_c3.addItem("")
        self.cbx_cat_c3.addItem("")
        self.cbox_man_2 = QtWidgets.QCheckBox(self.centralWidget)
        self.cbox_man_2.setGeometry(QtCore.QRect(290, 340, 120, 30))
        self.cbox_man_2.setObjectName("cbox_man_2")
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setGeometry(QtCore.QRect(20, 130, 721, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.min_fig3 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.min_fig3.setGeometry(QtCore.QRect(600, 380, 91, 30))
        self.min_fig3.setDecimals(5)
        self.min_fig3.setMinimum(-10000099.0)
        self.min_fig3.setMaximum(10000099.0)
        self.min_fig3.setObjectName("min_fig3")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(280, 90, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(20, 60, 721, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.min_fig1 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.min_fig1.setGeometry(QtCore.QRect(120, 380, 91, 30))
        self.min_fig1.setDecimals(5)
        self.min_fig1.setMinimum(-10000099.0)
        self.min_fig1.setMaximum(10000099.0)
        self.min_fig1.setObjectName("min_fig1")
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setGeometry(QtCore.QRect(250, 140, 20, 121))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_12 = QtWidgets.QLabel(self.centralWidget)
        self.label_12.setGeometry(QtCore.QRect(50, 380, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.cbox_man_3 = QtWidgets.QCheckBox(self.centralWidget)
        self.cbox_man_3.setGeometry(QtCore.QRect(530, 340, 120, 30))
        self.cbox_man_3.setObjectName("cbox_man_3")
        self.cshades = QtWidgets.QSpinBox(self.centralWidget)
        self.cshades.setGeometry(QtCore.QRect(650, 90, 50, 30))
        self.cshades.setMaximum(40)
        self.cshades.setObjectName("cshades")
        self.cbx_scat_c3 = QtWidgets.QComboBox(self.centralWidget)
        self.cbx_scat_c3.setGeometry(QtCore.QRect(520, 210, 200, 30))
        self.cbx_scat_c3.setObjectName("cbx_scat_c3")
        self.pb_plot = QtWidgets.QPushButton(self.centralWidget)
        self.pb_plot.setGeometry(QtCore.QRect(620, 280, 121, 30))
        self.pb_plot.setObjectName("pb_plot")
        self.cbox_man_1 = QtWidgets.QCheckBox(self.centralWidget)
        self.cbox_man_1.setGeometry(QtCore.QRect(50, 340, 120, 30))
        self.cbox_man_1.setObjectName("cbox_man_1")
        self.cbx_scat_c2 = QtWidgets.QComboBox(self.centralWidget)
        self.cbx_scat_c2.setGeometry(QtCore.QRect(280, 210, 200, 30))
        self.cbx_scat_c2.setObjectName("cbx_scat_c2")
        self.label_17 = QtWidgets.QLabel(self.centralWidget)
        self.label_17.setGeometry(QtCore.QRect(531, 420, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_13 = QtWidgets.QLabel(self.centralWidget)
        self.label_13.setGeometry(QtCore.QRect(50, 420, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.zoom_x = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.zoom_x.setGeometry(QtCore.QRect(170, 280, 91, 30))
        self.zoom_x.setDecimals(2)
        self.zoom_x.setMinimum(-10000099.0)
        self.zoom_x.setMaximum(10000099.0)
        self.zoom_x.setObjectName("zoom_x")
        self.cbx_scat_c1 = QtWidgets.QComboBox(self.centralWidget)
        self.cbx_scat_c1.setGeometry(QtCore.QRect(40, 210, 200, 30))
        self.cbx_scat_c1.setObjectName("cbx_scat_c1")
        self.cbx_cat_c2 = QtWidgets.QComboBox(self.centralWidget)
        self.cbx_cat_c2.setGeometry(QtCore.QRect(280, 160, 200, 30))
        self.cbx_cat_c2.setObjectName("cbx_cat_c2")
        self.cbx_cat_c2.addItem("")
        self.cbx_cat_c2.addItem("")
        self.cbx_cat_c2.addItem("")
        self.cbx_cat_c2.addItem("")
        self.cbx_cat_c2.addItem("")
        self.cbx_cat_c2.addItem("")
        self.cbx_cat_c2.addItem("")
        self.line_6 = QtWidgets.QFrame(self.centralWidget)
        self.line_6.setGeometry(QtCore.QRect(20, 250, 721, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.max_fig1 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.max_fig1.setGeometry(QtCore.QRect(120, 420, 91, 30))
        self.max_fig1.setDecimals(5)
        self.max_fig1.setMinimum(-10000099.0)
        self.max_fig1.setMaximum(10000099.0)
        self.max_fig1.setObjectName("max_fig1")
        self.cbox_zoom = QtWidgets.QCheckBox(self.centralWidget)
        self.cbox_zoom.setGeometry(QtCore.QRect(50, 280, 71, 30))
        self.cbox_zoom.setObjectName("cbox_zoom")
        self.max_fig2 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.max_fig2.setGeometry(QtCore.QRect(360, 420, 91, 30))
        self.max_fig2.setDecimals(5)
        self.max_fig2.setMinimum(-10000099.0)
        self.max_fig2.setMaximum(10000099.0)
        self.max_fig2.setObjectName("max_fig2")
        self.label_16 = QtWidgets.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(531, 380, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.min_fig2 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.min_fig2.setGeometry(QtCore.QRect(360, 380, 91, 30))
        self.min_fig2.setDecimals(5)
        self.min_fig2.setMinimum(-10000099.0)
        self.min_fig2.setMaximum(10000099.0)
        self.min_fig2.setObjectName("min_fig2")
        self.cbx_cat_c1 = QtWidgets.QComboBox(self.centralWidget)
        self.cbx_cat_c1.setGeometry(QtCore.QRect(40, 160, 200, 30))
        self.cbx_cat_c1.setObjectName("cbx_cat_c1")
        self.cbx_cat_c1.addItem("")
        self.cbx_cat_c1.addItem("")
        self.cbx_cat_c1.addItem("")
        self.cbx_cat_c1.addItem("")
        self.cbx_cat_c1.addItem("")
        self.cbx_cat_c1.addItem("")
        self.cbx_cat_c1.addItem("")
        self.pb_start = QtWidgets.QPushButton(self.centralWidget)
        self.pb_start.setGeometry(QtCore.QRect(40, 20, 200, 30))
        self.pb_start.setObjectName("pb_start")
        self.resolution = QtWidgets.QSpinBox(self.centralWidget)
        self.resolution.setGeometry(QtCore.QRect(150, 90, 91, 30))
        self.resolution.setMinimum(100)
        self.resolution.setMaximum(10000)
        self.resolution.setObjectName("resolution")
        self.label_18 = QtWidgets.QLabel(self.centralWidget)
        self.label_18.setGeometry(QtCore.QRect(150, 280, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_15 = QtWidgets.QLabel(self.centralWidget)
        self.label_15.setGeometry(QtCore.QRect(290, 420, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_19 = QtWidgets.QLabel(self.centralWidget)
        self.label_19.setGeometry(QtCore.QRect(290, 280, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.cbx_comp = QtWidgets.QComboBox(self.centralWidget)
        self.cbx_comp.setGeometry(QtCore.QRect(280, 20, 200, 30))
        self.cbx_comp.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbx_comp.setObjectName("cbx_comp")
        self.label_20 = QtWidgets.QLabel(self.centralWidget)
        self.label_20.setGeometry(QtCore.QRect(430, 280, 61, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.line_7 = QtWidgets.QFrame(self.centralWidget)
        self.line_7.setGeometry(QtCore.QRect(20, 320, 721, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralWidget)
        self.line_8.setGeometry(QtCore.QRect(20, 460, 721, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_5 = QtWidgets.QFrame(self.centralWidget)
        self.line_5.setGeometry(QtCore.QRect(250, 330, 20, 141))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_9 = QtWidgets.QFrame(self.centralWidget)
        self.line_9.setGeometry(QtCore.QRect(490, 330, 20, 141))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 762, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Colorshades"))
        self.cbx_legend.setItemText(0, _translate("MainWindow", "RdYlBu"))
        self.cbx_legend.setItemText(1, _translate("MainWindow", "RdBu"))
        self.cbx_legend.setItemText(2, _translate("MainWindow", "RdYlGn"))
        self.cbx_legend.setItemText(3, _translate("MainWindow", "YlOrRd"))
        self.cbx_legend.setItemText(4, _translate("MainWindow", "Spectral"))
        self.cbx_legend.setItemText(5, _translate("MainWindow", "coolwarm"))
        self.cbx_legend.setItemText(6, _translate("MainWindow", "bwr"))
        self.cbx_legend.setItemText(7, _translate("MainWindow", "seismic"))
        self.cbx_legend.setItemText(8, _translate("MainWindow", "jet"))
        self.cbx_legend.setItemText(9, _translate("MainWindow", "Greys"))
        self.label_2.setText(_translate("MainWindow", "Resolution"))
        self.pb_comp.setText(_translate("MainWindow", "comparison"))
        self.label_14.setText(_translate("MainWindow", "Min."))
        self.cbx_cat_c3.setItemText(0, _translate("MainWindow", "pressure"))
        self.cbx_cat_c3.setItemText(1, _translate("MainWindow", "u"))
        self.cbx_cat_c3.setItemText(2, _translate("MainWindow", "stress"))
        self.cbx_cat_c3.setItemText(3, _translate("MainWindow", "estress"))
        self.cbx_cat_c3.setItemText(4, _translate("MainWindow", "el. strain"))
        self.cbx_cat_c3.setItemText(5, _translate("MainWindow", "pl. strain"))
        self.cbx_cat_c3.setItemText(6, _translate("MainWindow", "tot. strain"))
        self.cbox_man_2.setText(_translate("MainWindow", "change min./max."))
        self.label.setText(_translate("MainWindow", "Color-Scale"))
        self.label_12.setText(_translate("MainWindow", "Min."))
        self.cbox_man_3.setText(_translate("MainWindow", "change min./max."))
        self.pb_plot.setText(_translate("MainWindow", "plot"))
        self.cbox_man_1.setText(_translate("MainWindow", "change min./max."))
        self.label_17.setText(_translate("MainWindow", "Max."))
        self.label_13.setText(_translate("MainWindow", "Max."))
        self.cbx_cat_c2.setItemText(0, _translate("MainWindow", "pressure"))
        self.cbx_cat_c2.setItemText(1, _translate("MainWindow", "u"))
        self.cbx_cat_c2.setItemText(2, _translate("MainWindow", "stress"))
        self.cbx_cat_c2.setItemText(3, _translate("MainWindow", "estress"))
        self.cbx_cat_c2.setItemText(4, _translate("MainWindow", "el. strain"))
        self.cbx_cat_c2.setItemText(5, _translate("MainWindow", "pl. strain"))
        self.cbx_cat_c2.setItemText(6, _translate("MainWindow", "tot. strain"))
        self.cbox_zoom.setText(_translate("MainWindow", "Zoom to:"))
        self.label_16.setText(_translate("MainWindow", "Min."))
        self.cbx_cat_c1.setItemText(0, _translate("MainWindow", "pressure"))
        self.cbx_cat_c1.setItemText(1, _translate("MainWindow", "u"))
        self.cbx_cat_c1.setItemText(2, _translate("MainWindow", "stress"))
        self.cbx_cat_c1.setItemText(3, _translate("MainWindow", "estress"))
        self.cbx_cat_c1.setItemText(4, _translate("MainWindow", "el. strain"))
        self.cbx_cat_c1.setItemText(5, _translate("MainWindow", "pl. strain"))
        self.cbx_cat_c1.setItemText(6, _translate("MainWindow", "tot. strain"))
        self.pb_start.setText(_translate("MainWindow", "Start"))
        self.label_18.setText(_translate("MainWindow", "X"))
        self.label_15.setText(_translate("MainWindow", "Max."))
        self.label_19.setText(_translate("MainWindow", "Y"))
        self.label_20.setText(_translate("MainWindow", "Extend"))

